# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cfriot <cfriot@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2014/11/05 16:32:13 by cfriot            #+#    #+#              #
#    Updated: 2014/11/08 15:57:21 by cfriot           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

FLAGS = -Wall -Werror -Wextra

SRC = 	ft_atoi.c			\
		ft_bzero.c			\
		ft_isalnum.c		\
		ft_isalpha.c		\
		ft_isascii.c		\
		ft_isdigit.c		\
		ft_isprint.c		\
		ft_itoa.c			\
		ft_lstnew.c			\
		ft_lstadd.c			\
		ft_lstdelone.c		\
		ft_lstdel.c			\
		ft_lstiter.c		\
		ft_lstmap.c			\
		ft_memalloc.c		\
		ft_memchr.c			\
		ft_memccpy.c		\
		ft_memcmp.c			\
		ft_memcpy.c			\
		ft_memdel.c			\
		ft_memmove.c		\
		ft_memset.c			\
		ft_putchar.c		\
	 	ft_putchar_fd.c		\
		ft_putendl.c		\
		ft_putendl_fd.c		\
		ft_putnbr.c			\
		ft_putnbr_fd.c		\
	  	ft_putstr.c			\
		ft_putstr_fd.c		\
	  	ft_strcat.c			\
	  	ft_strchr.c			\
		ft_strclr.c			\
	  	ft_strcmp.c			\
	  	ft_strcpy.c			\
		ft_strdel.c			\
	  	ft_strdup.c			\
		ft_strequ.c			\
		ft_striter.c		\
		ft_striteri.c		\
		ft_strjoin.c		\
	  	ft_strlcat.c		\
	  	ft_strlen.c			\
	  	ft_strncat.c		\
	  	ft_strncmp.c		\
	  	ft_strncpy.c		\
	  	ft_strnequ.c		\
		ft_strnew.c			\
	  	ft_strnstr.c		\
		ft_strmap.c			\
		ft_strmapi.c		\
		ft_strtrim.c		\
	  	ft_strrchr.c		\
		ft_strsplit.c		\
	  	ft_strstr.c			\
		ft_strsub.c			\
		ft_tolower.c		\
		ft_toupper.c

OBJ = $(SRC:.c=.o)

all: $(NAME)

$(NAME):
	@gcc $(FLAGS) -c $(SRC) -I.
	@ar rc $(NAME) $(OBJ)
	@ranlib $(NAME)
	@echo "Done"

clean:
	@/bin/rm -f $(OBJ)

fclean: clean
	@/bin/rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
